# Phase 1 creates PKI & CA infrastructure for all shards
#
# helm upgrade \
#  --install \
#  --values ./kind-values-phase1.yaml \
#  --namespace kcp-certs \
#  --create-namespace \
#  kcp-certificates ./charts/certificates
#
certificates:
  name: certs
  kcp:
    pki: true
    certs: false
  frontproxy:
    pki: true
    certs: false
  etcd:
    pki: true
    certs: false
  kine:
    pki: false
    certs: false
  cache:
    pki: true
    certs: false
  secretTemplate:
    enabled: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kcp-alpha,kcp-beta,kcp-proxy,kcp-cache,cert-manager,idp"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kcp-alpha,kcp-beta,kcp-proxy,kcp-cache,cert-manager,idp"

letsEncrypt:
  enabled: false
  staging:
    enabled: true
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: <your-email-address>

  production:
    enabled: true
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: <your-email-address>
