# certificates is bit tricky, as we need to create a certificate for the service account
# to be shared with all instances. So we do it at PKI state.
{{- if .Values.certificates.kcp.pki -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "certificates.kcp" . }}-service-account
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
spec:
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  commonName: {{ include "certificates.kcp" . }}-service-account
  secretName: {{ include "certificates.kcp" . }}-service-account-cert
  issuerRef:
    name: {{ include "certificates.kcp" . }}-service-account-issuer
    kind: Issuer
    group: cert-manager.io
{{- if .Values.certificates.secretTemplate.enabled }}
  secretTemplate:
{{- if .Values.certificates.secretTemplate.annotations }}
    annotations:
    {{- toYaml .Values.certificates.secretTemplate.annotations | nindent 6 }}
{{- end }}
{{- if .Values.certificates.secretTemplate.labels }}
    labels:
    {{- toYaml .Values.certificates.secretTemplate.labels | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
