{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cache.fullname" .}}-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "cache"
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/kcp/tls/ca/tls.crt
        server: "https://{{ include "cache.fullname" . }}:8012"
      name: cache
    contexts:
    - context:
        cluster: cache
        user: ""
      name: cache
    current-context: cache
    kind: Config
    preferences: {}
    users: null
{{- end }}
